# Generated by Django 3.1 on 2021-04-24 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knows_math', models.BooleanField(default=False)),
                ('knows_singing', models.BooleanField(default=False)),
                ('knows_music', models.BooleanField(default=False)),
                ('knows_drawing', models.BooleanField(default=False)),
                ('knows_video_editing', models.BooleanField(default=False)),
                ('knows_animation', models.BooleanField(default=False)),
                ('learn_math', models.BooleanField(default=False)),
                ('learn_singing', models.BooleanField(default=False)),
                ('learn_music', models.BooleanField(default=False)),
                ('learn_drawing', models.BooleanField(default=False)),
                ('learn_video_editing', models.BooleanField(default=False)),
                ('learn_animation', models.BooleanField(default=False)),
                ('description', models.TextField(default='I love to learn and teach!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
